FROM apache/airflow:2.10.2-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    build-essential && \
    apt-get clean

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]